language: ruby
rvm:
  - 2.4
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --check-html --allow-hash-href --assume-extension
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - bundle exec rspec
